# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_url',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
